-- Supabase Database Schema for Abhijeet Mishra Portfolio
-- Run this in your Supabase Dashboard SQL Editor (https://supabase.com/dashboard)

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.messages enable row level security;

-- Allow anonymous visitors to submit contact messages
create policy "Allow anonymous message submissions"
  on public.messages
  for insert
  with check (true);
